### ISSUE TITLE
Modded glowing ores bug

### ISSUE THREAD

**Issue by mpustovoi** [ComplementaryDevelopment/ComplementaryReimagined#66] opened 2023-12-23 10:15 UTC
I'm using Embeddium 0.2.13, Oculus 1.6.13 with Complementary Reimagined 5.1.1 (and also Sinytra Connector for some Fabric mods) on Forge 1.20.1.
Since the manual modded glowing ores support was added, I have added their IDs in _shaders\block.properties_ file into `block.10024=` field.
I don't use any texturepacks, that either modify ores' textures or add custom emissivenes.
Why is this a thing?
![image](https://github.com/ComplementaryDevelopment/ComplementaryReimagined/assets/92390626/caec06cc-6b49-48e9-92d0-ef244275a389)
This happens with all added ores without exception (Deeper and Darker, Universal Ores, Randomium Ore, Diamonds in the rough, etc). Sometimes these weird diagonals are more visible, somewhere less.
![image](https://github.com/ComplementaryDevelopment/ComplementaryReimagined/assets/92390626/230f5d91-67ea-467c-b35d-99cbab2801b8)
Idk maybe I should address this bug to Oculus team or somewhere else.
Btw, on Fabric modpack (Sodium, Iris) everything works completely fine.

**Comment by EminGT** [comment] 2023-12-23 14:42
This is a known issue but it doesn't look like something I can fix. It's caused by some external variable that the shader can't change

**Comment by mpustovoi** [comment] 2023-12-23 14:49
So, it's impossible to even guess the approximate area of the problem here, right?
Maybe it's an Oculus bug or something.

**Comment by EminGT** [comment] 2023-12-24 10:56
I can't diagnose the problem as it doesn't happen on my system unfortunately

**Comment by tovc** [comment] 2024-01-21 14:28
[Here](https://cdn.discordapp.com/attachments/975340372865744937/1198626712649470043/create_line_shader_test.zip) is a minimal prism instance where the issue occurs. The pack is using Sodium 0.5.3, Iris 1.6.11, Indium 1.0.27 and QFAPI 7.4.0+0.90.0. The Create version is a fork that works with Sodium 5.0+; that can be found [here](https://modrinth.com/mod/create-fabric-sodium-fix/versions), but I don't believe it is casuing the issue.

Import the instance via prism, start it up, load into the existing world, then enable the shaders via the video settings menu.

The result should be something similar to this.
![2024-01-21_21 52 49](https://github.com/ComplementaryDevelopment/ComplementaryReimagined/assets/49025619/5101f275-e2f2-41bf-808b-7a90edd3cdf5)

I'd be interested to see it *not* occurring, as the result is the same on both my desktop and laptop. I am using a Nvidia graphics card in both. I do have an AMD card I can test this with, if that's what you're using.

**Comment by tovc** [comment] 2024-01-21 14:45
The bug seems to occur on Iris, in addition to Oculus, so I'm not sure if that title is ncessarily correct. Would you like me to make my own bug report for Iris?

**Comment by mpustovoi** [comment] 2024-01-21 14:57
I have never encountered the error of glowing ores with Sodium 0.5+ and Iris, although I don't use Create and, accordingly, the fork of Sodium 0.5 that works with it. As for me Iris and Oculus are not the same thing, but if you say you had this issue too, I can change the title back.
I wrote this rather because of the difference between Forge and Fabric, but if you say that you also had this problem, I can change the title back.

**Comment by mpustovoi** [comment] 2024-01-21 14:59
In fact, I should probably report this bug to the Oculus team.

**Comment by tovc** [comment] 2024-01-21 15:48
You're welcome to attempt to recreate the issue via the instructions I provided. I've been told that the issue occurs on both NeoForge and Fabric, with Oculus and Iris.

I wouldn't report the issue to the Oculus team until there's some evidence that it is actually related to Oculus, and not Iris. Should probably wait for Emin to comment on it.

**Comment by tovc** [comment] 2024-01-21 19:34
The issue is caused by the shader sampling textures outside of the one intended, due to sampling exactly between textures. I've forked and fixed it. The fix will be in a future release.
https://github.com/tovc/ComplementaryReimagined/compare/main...fix-diagonal-lines-on-modded-ores

**Comment by mpustovoi** [comment] 2024-01-21 19:41
I admire your dedication. 👏🏻

**Comment by tovc** [comment] 2024-01-21 19:57
I've already talked with Emin about it. They don't use github as a development platform anyway, so I won't make a PR.

**Comment by mpustovoi** [comment] 2024-01-21 19:59
Got it.
So, are you saying there will be an official release with your fix or what?

**Comment by tovc** [comment] 2024-01-21 20:15
At some stage, yes. I don't know when that will be.

**Closed** 2024-01-24 21:43 UTC
Labels: Problem
