### ISSUE TITLE
Latest build broke Waystones mod feature (missing glyphs)

### ISSUE THREAD

**Issue by Mister-Curious** [ComplementaryDevelopment/ComplementaryReimagined#125] opened 2024-08-01 07:49 UTC
Greetings. I recently updated to 1.21 from 1.20.4. Upon launch of the latest game build, and latest Complimentary Shaders (Reimagined), there is a feature from the[ Waystones mod](ComplementaryUnbound_r5.1.1.zip) that is no longer working. 

Once a Waysone has been activated, there is a visual layer that becomes present (a luminescent glyph):

![image](https://github.com/user-attachments/assets/c54508cc-924b-475d-8f83-438dff9f6734)

However when I play the game with shaders activated it longer shows:

![image](https://github.com/user-attachments/assets/bf282467-b2d8-4584-bf5b-e743ea2ed183)

I contacted the mod author who has been very helpful in diagnosing the issue, however they have mentioned that the only recourse at this point is to contact the folks who maintain the shader mod. It is my hope that we can identify what is causing this to break, and find a fix. I did try almost all of the settings in the shader pack to see if there was something that would reenable the missing glyphs, however I was not able to locate any settings that restored them. 

**Waystones mod version:** 
waystones-fabric-1.21-21.0.8.jar

Shader Pack version:
ComplementaryUnbound_r5.1.1

It should be noted that this all worked fine when I was using previous versions of both mods that were made for 1.20.4. 

Thanks for your time.

**Comment by BlayTheNinth** [comment] 2024-08-01 07:57
For reference, the code in question:

https://github.com/TwelveIterationMods/Waystones/blob/1.21.x/common/src/main/java/net/blay09/mods/waystones/client/render/WaystoneRenderer.java#L56-L66

**Comment by EminGT** [comment] 2024-08-01 11:26
First of all, know that shader packs are not Minecraft version dependant. You can use any version of Complementary in any Minecraft version. With this information I want to ask you a couple things:

- Which version of Complementary were you using before?
- Did you try using that older version of Complementary in 1.21 as well to see if it still works?
- Why not try out the latest version of Complementary (r5.2.2) instead of r5.1.1?

**Comment by Mister-Curious** [comment] 2024-08-02 03:58
Thanks for the reply. To answer your questions:
> Which version of Complementary were you using before?
ComplementaryUnbound_r5.1.1 (it appears to be the same one as am I using now)

> Did you try using that older version of Complementary in 1.21 as well to see if it still works?
Since it's the same as mentioned above, then no. 

> Why not try out the latest version of Complementary (r5.2.2) instead of r5.1.1?
Tried this as suggested, however the issue is still present. 

Is there anything else I might try to see if I can get this to work? Perhaps checking out that coded linked in the previous reply might shed some light. I do not code, so I will not be able to glean anything from that. 

Thank you .

**Comment by Mister-Curious** [comment] 2024-08-09 09:55
Any chance someone could help with this still?

**Comment by Mister-Curious** [comment] 2024-08-21 08:25
Could anyone please provide some assistance? I really want to understand why this problem is happening, and what I might do to rectify the issue. Its been a couple of weeks since I last asked for help. 

Thanks

**Comment by sloraris** [comment] 2024-09-01 03:31
Here to add my shared experience. Was running 1.20.1, updated to Complementary Unbound r5.2.2 and everything was working fine. Jumped to 1.21 and now the glyphs do not show when shaders are enabled. I've tested every single setting I could find that might be related, along with adjusting setting for block entities and renderers. Shaders on, no glyphs. Shaders off, glyphs appear. Would love to have this working again because these waystones look fantastic with Complementary.
![2024-08-31_21 30 59](https://github.com/user-attachments/assets/33067952-ab69-4898-866d-d8ca50f433e0)
![2024-08-31_21 31 06](https://github.com/user-attachments/assets/bd5257c4-7501-4607-8c3a-ec7611bd2c1f)

**Comment by Mister-Curious** [comment] 2024-09-03 06:37
Glad its not just me. I ran all the same tests you did, with no results.

**Comment by BlayTheNinth** [comment] 2024-09-03 07:25
Seeing that sharestones work, which render in the same manner, I believe the issue is that in Vanilla, the alpha channel of the color is ignored, while with the shader, it's respected. 

Sharestones happen to set an opaque alpha, whereas waystones just relied on the alpha channel not being used and so used a color of `#FFFFFF` instead of `#FFFFFFFF`.

Please test with Waystones v21.1.3 to see if it solves the issue.

**Comment by sloraris** [comment] 2024-09-06 22:07
I finally got a chance to test this, and I can confirm it's working again! Thanks so much to both of you for your awesome work on these incredible projects.
![2024-09-06_16 06 33](https://github.com/user-attachments/assets/812d7664-8cb3-4ecd-9ab4-e6d2e4e6cd84)

**Comment by EminGT** [comment] 2024-09-16 16:51
Closing as it's fixed by the mod

**Closed by EminGT** 2024-09-16 16:51 UTC
Labels: Problem
