### ISSUE TITLE
Hand-held map rendering issues

### ISSUE THREAD

**Issue by 704009905** [ComplementaryDevelopment/ComplementaryReimagined#16] opened 2023-04-27 08:27 UTC
Using ComplementaryReimagined r2.0.3.
Map renders have a "/" divide from upper-right to lower-left when viewing from specific angles.
![image](https://user-images.githubusercontent.com/11241929/234802719-c3d3cd44-3981-411d-ba48-de7ee8225ea1.png)
![image](https://user-images.githubusercontent.com/11241929/234803447-dacd1627-dfdf-4b14-a1e1-c3fa3b57efa5.png)
When Generated Normals is on, map render is also affected, which is possibly unintentional (but I feel good about this).
![image](https://user-images.githubusercontent.com/11241929/234803677-afe348d2-1a84-46a8-9225-fdec3170ebc9.png)
Differences are subtle, please open the original image.

**Comment by EminGT** [comment] 2023-04-27 09:48
The first kind of map rendering problems are caused by Optifine or Iris. Updating to the latest version of either can fix problems for some people. Other than that I can't really do much about them. The generated normals problem might be fixed in the latest version of Reimagined

**Comment by 704009905** [comment] 2023-05-12 12:31
> The first kind of map rendering problems are caused by Optifine or Iris.
Thanks for your reply. I recalled that this kind of problems are common, both with optifine and iris. So it's probably caused by them. Specifically, I use Oculus 1.2.8 for forge 1.19.2.
> The generated normals problem might be fixed in the latest version of Reimagined
Tested with [ComplementaryReimagined_r2.0.3.zip](https://github.com/ComplementaryDevelopment/ComplementaryReimagined/releases/download/latest/ComplementaryReimagined_r2.0.3.zip), the issue still occurs.

**Comment by EminGT** [comment] 2023-05-12 13:03
Oculus is not a supported platform to run shaderpacks unfortunately. It's a sloppy port of Iris made by someone that doesn't seem to care about issues. Also Reimagined r2.0.3 is an outdated version of the pack. You might or might not get better results on the latest version depending on the problem being caused by Oculus or not

**Comment by EminGT** [comment] 2023-06-23 15:25
Closing as it's unclear if the issue happens in the latest version on a supported vanilla platform. Feel free to make a new issue if you can reproduce a problem in those conditions

**Closed by EminGT** 2023-06-23 15:25 UTC
