### ISSUE TITLE
Noise artifacts in the nether, when used with Distant Horizons

### ISSUE THREAD

**Issue by EeveeEuphoria** [ComplementaryDevelopment/ComplementaryReimagined#115] opened 2024-07-17 17:50 UTC
For some reason, in the Nether only (haven't reached the End in my playthrough yet, might be a problem there too), there's this weird noisy texture that appears. If I move around, it follows my camera. It seems most prominent when looking in the direction of a soul sands valley. It also changes appearance whenever I change the settings around, but never completely goes away.
As the title suggests, if I disable Distant Horizons, this issue goes away entirely.

![2024-07-17_13 40 41](https://github.com/user-attachments/assets/7ab94af7-5e05-4b1d-8be3-843d56036949)
![2024-07-17_13 49 14](https://github.com/user-attachments/assets/bf73d6a0-84d0-477f-ade3-e6c5180fb575)

Minecraft 1.21, using Fabulously Optimized 6.0.0-beta.4, along with BedrockIfy, BetterDays, and Terralith

Running on Bazzite Linux (Fedora 40 Kionite), on Linux Kernel 6.9.6-201.fsync.fc40.x86_64, w/ AMD Ryzen 5 5600G and AMD Radeon RX 6600 XT, and on Wayland.

Settings used:
[ComplementaryReimagined_r5.2.2.zip.txt](https://github.com/user-attachments/files/16272808/ComplementaryReimagined_r5.2.2.zip.txt)

**Comment by EeveeEuphoria** [comment] 2024-07-17 17:55
Here's a couple of additional screenshots showing how this looks in a different biome, the effect is less noticeable, but still present. Two screenshots to help identify where the artifacts are present.
![2024-07-17_13 54 30](https://github.com/user-attachments/assets/05225b93-948a-497b-954a-c8335c540672)
![2024-07-17_13 54 29](https://github.com/user-attachments/assets/2c2fa3ff-4f88-47dd-9158-8d793191eb84)

**Comment by EminGT** [comment] 2024-07-17 22:29
Did you try not touching absolutely any settings at all after a restart to your game? Distant Horizons with Iris has problems with setting changes causing problems until the game is restarted

**Comment by EeveeEuphoria** [comment] 2024-07-18 03:24
Yeah, it looks like this if I just load into the world, and don't change a single setting at all. The most I do is refresh resource packs since some of my textures are strangely glitched (I think whatever's responsible for connected textures is to blame), but even if I forget to do that, this noise pattern still persists.

**Comment by EminGT** [comment] 2024-07-23 10:00
Closing as doesn't seem to be an issue directly caused by Complementary

**Closed by EminGT** 2024-07-23 10:00 UTC
