### ISSUE TITLE
Z-fighting on Chicken feet with Intense TAA

### ISSUE THREAD

**Issue by LessThanBenji** [ComplementaryDevelopment/ComplementaryReimagined#94] opened 2024-03-19 11:40 UTC
I've noticed Chickens' flat footsies often exhibit quite jarring z-fighting behavior with the ground, no matter what block they're standing on.

**Comment by EminGT** [comment] 2024-03-21 16:11
I can't reproduce this problem. No z-fighting for me. Can you take a video with the F3 menu enabled?

**Comment by LessThanBenji** [comment] 2024-03-22 05:27
No problem! The quality of this recording is awful because I used Windows Screen Capture in a 1366x768 window, so my apologies -- hopefully you can still see enough of the issue! The framerate of the recording is quite low so the z-fighting doesn't appear as vivid and jarring as it is in reality, I'd say the flickering rate is about double what it seems in the video. I recorded this in an isolated environment with nothing but Complementary Reimagined (v5.1.1) and its required dependencies (Iris (v1.6.17) and Sodium (v0.5.8) in 1.20.1, on Fabric 0.15.6. I have customized the shader's settings significantly, I'll try work out if it's a particular setting I've got on/off/changed causing this issue.

https://github.com/ComplementaryDevelopment/ComplementaryReimagined/assets/63028933/2695e50b-c44a-4d36-9c7b-d6618fc0175c

**Comment by LessThanBenji** [comment] 2024-03-22 05:33
I've figured it out! It's Camera > TAA Behaviour. I had it set to "Intense". Reverting this back to the default "Smart & Subtle" caused the z-fighting to cease immediately. I should've worked that out earlier given the setting literally has a warning stating it "will cause extra smudging and flickering" 😆

**Comment by EminGT** [comment] 2024-03-24 12:27
Should be fixed in upcoming r5.2

**Closed by EminGT** 2024-03-24 12:27 UTC
Labels: Problem
